import { sql, type SQL } from 'drizzle-orm';
import { customType, text, timestamp, uuid } from 'drizzle-orm/pg-core';
import { newId } from '@/lib/ids';

/** Case-insensitive text (emails). Requires the `citext` extension (migration 0000). */
export const citext = customType<{ data: string }>({
  dataType: () => 'citext',
});

/** UUIDv7 primary key generated by the application (docs/03 §1). */
export const pk = (name = 'id') => uuid(name).primaryKey().$defaultFn(newId);

/**
 * Text primary key for tables owned by Better Auth. The library supplies its own ids for some
 * records (e.g. verification rows keyed by a hashed token), which are not UUIDs.
 */
export const textPk = (name = 'id') => text(name).primaryKey().$defaultFn(newId);

export const tstz = (name: string) => timestamp(name, { withTimezone: true, mode: 'date' });
export const createdAt = () => tstz('created_at').notNull().defaultNow();
export const updatedAt = () =>
  tstz('updated_at')
    .notNull()
    .defaultNow()
    .$onUpdateFn(() => new Date());

/**
 * `<column> IN ('a','b',…)` for CHECK constraints. Values come from the constant
 * arrays in ./enums.ts (never from user input), so literal SQL is safe here.
 */
export function oneOf(column: string, values: readonly string[]): SQL {
  const list = values.map((v) => `'${v.replaceAll("'", "''")}'`).join(', ');
  return sql.raw(`${column} IN (${list})`);
}
